import { readdir } from 'node:fs/promises';
import { join } from 'node:path';
import { ensureDirectory, exists, listFiles, writeTextFile } from './utils/fs.js';

const BASE_PAGE_STYLES = `
      body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; margin: 2rem; line-height: 1.5; }
      h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
      nav { margin-bottom: 1rem; }
      ul { padding-left: 1.25rem; }
      code { background: #f6f8fa; padding: 0.1rem 0.3rem; border-radius: 4px; }
      .desc { color: #444; margin-bottom: 1rem; }
      .hint { color: #555; margin-top: 1rem; font-size: .95rem; }
      footer { margin-top: 2rem; font-size: 0.9rem; color: #666; }
`;

interface PageDefinition {
  readonly title: string;
  readonly body: string;
}

/**
 * Escapes special HTML characters.
 */
function htmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function buildList(
  items: readonly string[],
  renderItem: (item: string) => string,
  empty: string,
): string {
  return items.length > 0 ? items.map(renderItem).join('\n') : empty;
}

function renderPage({ title, body }: PageDefinition): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${title}</title>
    <style>
${BASE_PAGE_STYLES}
    </style>
  </head>
  <body>
${body}
  </body>
</html>
`;
}

function buildIndexJson<T extends object>(data: T, generatedAt: string): string {
  return JSON.stringify({ ...data, generatedAt }, null, 2);
}

/**
 * Builds the root index HTML page listing all available years.
 */
function buildRootIndex(years: readonly string[]): string {
  const sortedYears = years.slice().sort();
  const yearLinks = buildList(
    sortedYears,
    (year) => `      <li><a href="./${htmlEscape(year)}/">${htmlEscape(year)}</a></li>`,
    '      <li><em>No years yet</em></li>',
  );

  return renderPage({
    title: 'KVV Ausfälle — Data Index',
    body: `
    <h1>KVV Ausfälle — Data Index</h1>
    <p class="desc">
      Static data files generated by the scraper. Browse into a year to see available JSON files.
    </p>

    <h2>Years</h2>
    <ul>
${yearLinks}
    </ul>

    <footer>
      <p>Site root is <code>docs/</code>. If a directory doesn't list files, try navigating directly by URL.</p>
    </footer>
`,
  });
}

/**
 * Builds a year index HTML page listing all JSON files for that year.
 */
function buildYearIndex(year: string, files: readonly string[]): string {
  const sortedFiles = files.slice().sort();
  const fileLinks = buildList(
    sortedFiles,
    (file) =>
      `      <li><a href="./${encodeURIComponent(file)}"><code>${htmlEscape(file)}</code></a></li>`,
    '      <li><em>No files yet</em></li>',
  );

  return renderPage({
    title: `KVV Ausfälle — ${htmlEscape(year)}`,
    body: `
    <nav><a href="../">← Back to index</a></nav>
    <h1>KVV Ausfälle — ${htmlEscape(year)}</h1>
    <p>JSON data files generated by the scraper for ${htmlEscape(year)}.</p>

    <h2>Files</h2>
    <ul>
${fileLinks}
    </ul>

    <p class="hint">If additional files are added (e.g., for other lines), they will appear automatically on next run.</p>
`,
  });
}

/**
 * Builds the root index JSON listing all available years.
 */
function buildRootIndexJson(years: readonly string[], generatedAt: string): string {
  return buildIndexJson({ years: years.slice().sort() }, generatedAt);
}

/**
 * Builds a year index JSON listing all JSON files for that year.
 */
function buildYearIndexJson(year: string, files: readonly string[], generatedAt: string): string {
  return buildIndexJson({ year, files: files.slice().sort() }, generatedAt);
}

const YEAR_PATTERN = /^\d{4}$/;

/**
 * Finds all year directories (4-digit names) in the base directory.
 */
async function findYears(baseDir: string): Promise<string[]> {
  if (!(await exists(baseDir))) {
    return [];
  }

  const entries = await readdir(baseDir, { withFileTypes: true });
  return entries.filter((d) => d.isDirectory() && YEAR_PATTERN.test(d.name)).map((d) => d.name);
}

/**
 * Lists all JSON files in a directory.
 */
async function listJsonFiles(dir: string): Promise<string[]> {
  const entries = await listFiles(dir);
  return entries.filter((name) => name.toLowerCase().endsWith('.json'));
}

/**
 * Generates HTML and JSON index pages for the site.
 * Creates a root index listing all years and per-year indices listing JSON files.
 */
export async function generateSiteIndices(baseDir: string): Promise<void> {
  // Ensure base directory exists
  await ensureDirectory(baseDir);

  const years = await findYears(baseDir);
  const generatedAt = new Date().toISOString();

  // Generate root indices (HTML and JSON)
  const rootHtml = buildRootIndex(years);
  const rootJson = buildRootIndexJson(years, generatedAt);
  await Promise.all([
    writeTextFile(join(baseDir, 'index.html'), rootHtml),
    writeTextFile(join(baseDir, 'index.json'), rootJson),
  ]);

  // Generate per-year indices (HTML and JSON)
  await Promise.all(
    years.map(async (year) => {
      const yearDir = join(baseDir, year);
      const files = await listJsonFiles(yearDir);
      const html = buildYearIndex(year, files);
      const json = buildYearIndexJson(year, files, generatedAt);
      await Promise.all([
        writeTextFile(join(yearDir, 'index.html'), html),
        writeTextFile(join(yearDir, 'index.json'), json),
      ]);
    }),
  );
}
